ALTER TABLE diary_analysis
    ALTER COLUMN target_date TYPE TIMESTAMP USING target_date::TIMESTAMP;

ALTER TABLE diary_analysis
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE diary_analysis
    ADD COLUMN modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE conversation_analysis
    ADD COLUMN is_ai_initiated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE conversation_analysis
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE conversation_analysis
    ADD COLUMN modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
