CREATE TABLE status_cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID      NOT NULL,
    date        DATE      NOT NULL,
    title       VARCHAR   NOT NULL,
    description VARCHAR   NOT NULL,
    sub_title   VARCHAR   NOT NULL,
    suggestion  VARCHAR   NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);