apiVersion: apps/v1
kind: Deployment
metadata:
  name: bio-ml-service
  namespace: rebloom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: bio-ml-service
  template:
    metadata:
      labels:
        app: bio-ml-service
    spec:
      containers:
        - name: bio-ml-service
          image: cramfull99/rebloom-bio-ml:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: bio-ml-config
            - secretRef:
                name: bio-ml-secret
          volumeMounts:
            - name: bio-ml-models
              mountPath: /app/model
      volumes:
        - name: bio-ml-models
          emptyDir: { }
