debug: true

logging:
  level:
    root: INFO

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29093,localhost:29094}

  devtools:
    restart:
      enabled: false

