debug: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.apache.kafka: INFO
    io.lettuce: INFO

spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

  devtools:
    restart:
      enabled: false
