apiVersion: v1
kind: ConfigMap
metadata:
  name: report-config
  namespace: rebloom
data:
  SERVER_PORT: "8084"
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "k14b109.p.ssafy.io"
  DB_PORT: "5432"
  DB_NAME: "rebloom_report"
  DB_SSL_MODE: "disable"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  RUNPOD_ENDPOINT_ID: "b67cjf4svf99yn"
  RUNPOD_BASE_URL: "https://api.runpod.ai/v2"
  RUNPOD_WAIT_MS: "120000"
  RECENT_INSIGHT_API_URL: "https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions"
  BIOMETRIC_SERVICE_URL: "http://biometric-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
  KAFKA_BOOTSTRAP_SERVERS: "k14b109.p.ssafy.io:19092,k14b109.p.ssafy.io:19093,k14b109.p.ssafy.io:19094"
  KAFKA_TOPIC_PARENT_REPORT_CREATED: "rebloom.parent-report.created.v1"
  KAFKA_TOPIC_PARENT_REPORT_COMMENT_CREATED: "rebloom.parent-report-comment.created.v1"
  KAFKA_TOPIC_STATUS_CARD_CREATED: "rebloom.status-card.created.v1"
  KAFKA_TOPIC_EVENT_DLT: "rebloom.event.dlt.v1"
  TZ: "Asia/Seoul"
  JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Seoul"
