-- 기존 의존성 제거 (순서 중요)
DROP TABLE IF EXISTS notification_schedules CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS user_fcm_tokens CASCADE;
DROP TABLE IF EXISTS notification_settings CASCADE;
DROP TABLE IF EXISTS notification_types CASCADE;

DROP TYPE IF EXISTS notification_type CASCADE;
DROP TYPE IF EXISTS delivery_status CASCADE;
DROP TYPE IF EXISTS schedule_day CASCADE;


CREATE TYPE delivery_status AS ENUM (
    'PENDING',
    'SENT',
    'FAILED'
);

CREATE TYPE schedule_day AS ENUM (
    'MONDAY',
    'TUESDAY',
    'WEDNESDAY',
    'THURSDAY',
    'FRIDAY',
    'SATURDAY',
    'SUNDAY'
);

CREATE TABLE notification_types(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR NOT NULL UNIQUE,
   PRIMARY KEY (id)
);

INSERT INTO notification_types (name) VALUES
  ('RISK_ALERT'),
  ('CONVERSATION_ALERT'),
  ('DIARY_REPORT'),
  ('CONVERSATION_REPORT'),
  ('PARENT_REPORT_NEW'),
  ('PARENT_REPORT_REPLY'),
  ('DIARY_REMINDER');

-- FCM 토큰 관리 테이블 (user_fcm_tokens)
CREATE TABLE user_fcm_tokens (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     user_id UUID NOT NULL,
     fcm_token VARCHAR(512) NOT NULL UNIQUE,
     is_active BOOLEAN NOT NULL DEFAULT true,
     created_at TIMESTAMP NOT NULL,
     modified_at TIMESTAMP NOT NULL,
     PRIMARY KEY (id)
);

CREATE INDEX idx_user_fcm_tokens_user_active
    ON user_fcm_tokens (user_id, is_active);

-- 알림 설정 테이블 (notification_settings)
CREATE TABLE notification_settings (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id UUID UNIQUE,
   is_enabled BOOLEAN NOT NULL DEFAULT true,
   created_at TIMESTAMP NOT NULL,
   modified_at TIMESTAMP NOT NULL,
   PRIMARY KEY (id)
);

-- 알림 스케줄 테이블 (notification_schedules)
CREATE TABLE notification_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    notification_type_id BIGINT NOT NULL,
    day schedule_day NOT NULL,
    time TIME NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_schedules_notification_type
        FOREIGN KEY (notification_type_id) REFERENCES notification_types(id)
);

CREATE INDEX idx_notification_schedules_user_type
    ON notification_schedules (user_id, notification_type_id);

CREATE INDEX idx_notification_schedules_day_time
    ON notification_schedules (day, time);

-- 알림 내역 테이블 (notifications)
CREATE TABLE notifications (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   receiver_id UUID NOT NULL,
   notification_type_id BIGINT NOT NULL,
   payload JSONB NOT NULL,
   is_read BOOLEAN NOT NULL DEFAULT false,
   delivery_status delivery_status NOT NULL DEFAULT 'PENDING',
   created_at TIMESTAMP NOT NULL,
   modified_at TIMESTAMP NOT NULL,
   PRIMARY KEY (id),
   CONSTRAINT fk_notifications_type
       FOREIGN KEY (notification_type_id)
           REFERENCES notification_types(id)
);


CREATE INDEX idx_notifications_receiver_created
    ON notifications (receiver_id, created_at DESC);

CREATE INDEX idx_notifications_receiver_read_created
    ON notifications (receiver_id, is_read, created_at DESC);