plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.13'
	id 'io.spring.dependency-management' version '1.1.7'
}

apply from: file('../../common-service.gradle')

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.kafka:spring-kafka'
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	testImplementation 'org.springframework.kafka:spring-kafka-test'

	// security module
	implementation project(':modules:security-module')

	implementation project(':modules:event-module')
	implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
	implementation 'com.google.firebase:firebase-admin:9.7.0'

	implementation "net.javacrumbs.shedlock:shedlock-spring:7.6.0"
	implementation "net.javacrumbs.shedlock:shedlock-provider-redis-spring:7.6.0"
}
