apiVersion: v1
kind: Secret
metadata:
  name: bio-ml-secret
  namespace: rebloom
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<replace-me>"
  AWS_SECRET_ACCESS_KEY: "<replace-me>"
  GMS_KEY: "<replace-me>"
