apiVersion: v1
kind: Secret
metadata:
  name: report-secret
  namespace: rebloom
type: Opaque
stringData:
  DB_USERNAME: "<replace-me>"
  DB_PASSWORD: "<replace-me>"
  RUNPOD_API_KEY: "<replace-me>"
  RECENT_INSIGHT_API_KEY: "<replace-me>"
