-- children_parent_relations 테이블 id 컬럼 IDENTITY 속성 추가
ALTER TABLE children_parent_relations
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- parent_counselor_relations 테이블 id 컬럼 IDENTITY 속성 추가
ALTER TABLE parent_counselor_relations
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- devices 테이블 id 컬럼 타입 변경 및 IDENTITY 추가 (UUID -> BIGINT)
ALTER TABLE devices DROP CONSTRAINT devices_pkey CASCADE;
ALTER TABLE devices DROP COLUMN id;
ALTER TABLE devices ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;