CREATE TYPE user_role AS ENUM ('CHILD', 'PARENT', 'COUNSELOR');
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');
CREATE TYPE relation_status AS ENUM ('ACTIVE', 'PENDING', 'REJECT');
CREATE TYPE user_status AS ENUM('ACTIVE', 'WITHDRAW');

CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    phone VARCHAR NOT NULL,
    role user_role NOT NULL,
    status user_status NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL
);

CREATE TABLE childrens (
    id UUID PRIMARY KEY,
    birth VARCHAR NOT NULL,
    gender gender NOT NULL,
    address VARCHAR NOT NULL,
    address_detail VARCHAR NOT NULL,
    CONSTRAINT fk_childrens_user
        FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE parents (
    id UUID PRIMARY KEY,
    code VARCHAR NOT NULL,
    CONSTRAINT fk_parents_user
        FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE counselors (
    id UUID PRIMARY KEY,
    hospital_name VARCHAR NOT NULL,
    hospital_address VARCHAR NOT NULL,
    CONSTRAINT fk_counselors_user
        FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE social_users (
    id UUID PRIMARY KEY,
    provider VARCHAR NOT NULL,
    provider_user_id VARCHAR NOT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT fk_social_users_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE children_parent_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_status relation_status NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL,
    children_id UUID NOT NULL,
    parent_id UUID NOT NULL,
    CONSTRAINT fk_children_parent_child
        FOREIGN KEY (children_id) REFERENCES childrens(id),
    CONSTRAINT fk_children_parent_parent
        FOREIGN KEY (parent_id) REFERENCES parents(id)
);

CREATE TABLE children_counselor_relations (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL,
    relation_status relation_status NOT NULL
);

CREATE TABLE parent_counselor_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    relation_status relation_status NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL,
    counselor_id UUID NOT NULL,
    parent_id UUID NOT NULL,
    CONSTRAINT fk_parent_counselor_counselor
        FOREIGN KEY (counselor_id) REFERENCES counselors(id),
    CONSTRAINT fk_parent_counselor_parent
        FOREIGN KEY (parent_id) REFERENCES parents(id)
);

CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR NOT NULL,
    paired_at TIMESTAMP NOT NULL,
    is_paired BOOLEAN NOT NULL,
    parent_id UUID NOT NULL,
    CONSTRAINT fk_devices_parent
        FOREIGN KEY (parent_id) REFERENCES parents(id)
);
