DROP TABLE IF EXISTS children_counselor_relations;

CREATE TABLE children_counselor_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counselor_id UUID NOT NULL,
    children_id UUID NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    relation_status relation_status NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_children_counselor_counselor
        FOREIGN KEY (counselor_id) REFERENCES counselors(id),
    CONSTRAINT fk_children_counselor_children
        FOREIGN KEY (children_id) REFERENCES childrens(id)
);

CREATE INDEX idx_children_counselor_relations_counselor_children
    ON children_counselor_relations (counselor_id, children_id);

CREATE INDEX idx_children_counselor_relations_children
    ON children_counselor_relations (children_id);

CREATE UNIQUE INDEX uq_active_children_counselor_relation
    ON children_counselor_relations (counselor_id, children_id)
    WHERE ended_at IS NULL;
