-- Device pairing is now modeled as "a device row exists for a child".
-- Existing rows were parent-only mappings, so they cannot be safely migrated.
DELETE FROM devices;

ALTER TABLE devices DROP CONSTRAINT IF EXISTS fk_devices_parent;
ALTER TABLE devices DROP CONSTRAINT IF EXISTS fk_devices_children;
ALTER TABLE devices DROP CONSTRAINT IF EXISTS fk_devices_registered_parent;

DO $$
DECLARE
    id_data_type TEXT;
BEGIN
    SELECT data_type
    INTO id_data_type
    FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'devices'
      AND column_name = 'id';

    IF id_data_type = 'uuid' THEN
        ALTER TABLE devices DROP CONSTRAINT IF EXISTS devices_pkey CASCADE;
        ALTER TABLE devices DROP COLUMN id;
        ALTER TABLE devices ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
END $$;

ALTER TABLE devices
    DROP COLUMN IF EXISTS parent_id,
    DROP COLUMN IF EXISTS registered_by_parent_id,
    DROP COLUMN IF EXISTS paired_at,
    DROP COLUMN IF EXISTS is_paired;

ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS device_type VARCHAR,
    ADD COLUMN IF NOT EXISTS children_id UUID;

ALTER TABLE devices
    ALTER COLUMN device_type SET NOT NULL,
    ALTER COLUMN children_id SET NOT NULL;

ALTER TABLE devices
    ADD CONSTRAINT fk_devices_children
        FOREIGN KEY (children_id) REFERENCES childrens(id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_devices_serial_number
    ON devices (serial_number);

CREATE UNIQUE INDEX IF NOT EXISTS uq_devices_children_device_type
    ON devices (children_id, device_type);
