spring:
  application:
    name: gateway-service
  jackson:
    time-zone: Asia/Seoul
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: biometric-service
          uri: ${BIOMETRIC_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/biometric/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: ${REPORT_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI:http://localhost:8085}
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: emotion-inference-service
          uri: ${EMOTION_INFERENCE_SERVICE_URI:http://localhost:8003}
          predicates:
            - Path=/emotion-inference/**
          filters:
            - StripPrefix=1
        - id: aiot-ai-service
          uri: ${AIOT_AI_SERVICE_URI:http://localhost:8001}
          predicates:
            - Path=/aiot-ai/**
          filters:
            - StripPrefix=1
        - id: bio-ml-service
          uri: ${BIO_ML_SERVICE_URI:http://localhost:8002}
          predicates:
            - Path=/bio-ml/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:8080}
