apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rebloom-proof
  region: ap-northeast-2

availabilityZones:
  - ap-northeast-2a
  - ap-northeast-2c

managedNodeGroups:
  - name: rebloom-proof-ng
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    privateNetworking: false
    labels:
      workload: rebloom-proof
    tags:
      Purpose: rebloom-proof
      Project: ReBloom

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
