-- stress_score 테이블 변경사항
ALTER TABLE stress_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE stress_score ADD COLUMN created_at TIMESTAMP NOT NULL;
ALTER TABLE stress_score ADD COLUMN modified_at TIMESTAMP NOT NULL;

-- daily_rhythm_stats 테이블 변경사항
ALTER TABLE daily_rhythm_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- status_cards 테이블 컬럼명 오타 수정
ALTER TABLE status_cards RENAME COLUMN sugget_comment TO suggest_comment;