-- biometrics 테이블: is_sleeping 컬럼 삭제
ALTER TABLE biometrics DROP COLUMN is_sleeping;

-- sleeps 테이블: sdk_updated_at 컬럼 삭제
ALTER TABLE sleeps DROP COLUMN sdk_updated_at;

-- 감지된 이상치 저장 테이블
CREATE TABLE anomalies (
         id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
         user_id   UUID      NOT NULL,
         ts_start      TIMESTAMP NOT NULL,
         ts_end        TIMESTAMP NOT NULL,
         hr            FLOAT,
         rmssd         FLOAT,
         pnn50         FLOAT,
         lf_hf         FLOAT,
         acc_mag       FLOAT,
         hr_acc_ratio  FLOAT,
         is_anomaly    BOOLEAN, -- NULL: 미실행 / true: 확정 / false: 오탐
         PRIMARY KEY (id)
);

CREATE INDEX idx_anomaly_children_ts ON anomalies (user_id, ts_start DESC);