-- 기존 V1.x 테이블 삭제 (V2 전면 개편)
DROP TABLE IF EXISTS status_cards;
DROP TABLE IF EXISTS daily_rhythm_stats;
DROP TABLE IF EXISTS stress_score;
DROP TABLE IF EXISTS minutely_health_logs;

-- 신규 V2 테이블 생성
CREATE TABLE biometrics (
                            user_id           UUID        NOT NULL,
                            ts_start          TIMESTAMP   NOT NULL,
                            ts_end            TIMESTAMP   NOT NULL,
                            is_sleeping       BOOLEAN     NOT NULL,
                            hr                FLOAT,
                            ibi               FLOAT,
                            rmssd             FLOAT,
                            pnn50             FLOAT,
                            lf_hf             FLOAT,
                            acc_x_avg         FLOAT,
                            acc_y_avg         FLOAT,
                            acc_z_avg         FLOAT,
                            acc_mag           FLOAT,
                            hr_acc_ratio      FLOAT,
                            missingness_score FLOAT,
                            PRIMARY KEY (user_id, ts_start)
);

CREATE TABLE sleeps (
                        user_id          UUID        NOT NULL,
                        date             DATE        NOT NULL,
                        asleep           TIMESTAMP,
                        wakeup           TIMESTAMP,
                        sleep_duration   FLOAT,
                        waso             FLOAT,
                        sleep_score      FLOAT,
                        sleep_efficiency FLOAT,
                        sdk_updated_at   TIMESTAMP,
                        PRIMARY KEY (user_id, date)
);

CREATE TABLE phq_results (
                             id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             user_id      UUID         NOT NULL,
                             date         DATE         NOT NULL,
                             result       SMALLINT     NOT NULL,
                             score        FLOAT        NOT NULL,
                             predicted_at TIMESTAMP    NOT NULL,
                             PRIMARY KEY (id)
);

-- V2 인덱스
CREATE INDEX idx_phq_user_date ON phq_results(user_id, date DESC);