group = 'com.ssafy.rebloom'
version = '0.0.1-SNAPSHOT'

def serviceProjects = [
        project(':services:gateway-service'),
        project(':services:auth-service'),
        project(':services:biometric-service'),
        project(':services:ai-service'),
        project(':services:notification-service'),
        project(':services:report-service')
]

configure(serviceProjects) {
    group = 'com.ssafy.rebloom'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        dependencies {
            compileOnly 'org.projectlombok:lombok'
            annotationProcessor 'org.projectlombok:lombok'
            testCompileOnly 'org.projectlombok:lombok'
            testAnnotationProcessor 'org.projectlombok:lombok'

            implementation 'org.springframework.boot:spring-boot-starter-actuator'
            implementation 'org.springframework.boot:spring-boot-starter-validation'
            testImplementation 'org.springframework.boot:spring-boot-starter-test'
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

            if (!project.hasProperty('skipDefaultWebServiceDependencies')) {
                implementation project(':modules:common-module')
                implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
                implementation 'org.springframework.boot:spring-boot-starter-web'
                implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.17'
                implementation 'org.flywaydb:flyway-core'
                implementation 'org.flywaydb:flyway-database-postgresql'
                runtimeOnly 'org.postgresql:postgresql'
            }
        }

        tasks.named('test') {
            useJUnitPlatform()
        }
    }

    pluginManager.withPlugin('org.springframework.boot') {
        dependencies {
            developmentOnly 'org.springframework.boot:spring-boot-devtools'
        }
    }

    pluginManager.withPlugin('io.spring.dependency-management') {
        dependencyManagement {
            imports {
                mavenBom 'org.springframework.boot:spring-boot-dependencies:3.5.13'
                mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2025.0.2'
            }
        }
    }
}
