rootProject.name = 'rebloom'

// services
include 'services:gateway-service'
include 'services:auth-service'
include 'services:biometric-service'
include 'services:ai-service'
include 'services:notification-service'
include 'services:report-service'

// modules
include 'modules:common-module'
include 'modules:security-module'
include 'modules:event-module'